# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f05b5aa1854c3d6ff8fc3f0b9ddb3e771a2ca9ce9f47cd63e74cd1232571e2f2229af4493b7ac1437ae767189c0a12bc01aed9331b00da93743e04038356828f

test:
  secret_key_base: 9778eb645b6f8cf85abe33b1ed3f431d056638e24e5ee2d0fcf9c5a106dce1c10169db466382de7433a1f1faaf227997fcba916cc640b7993666a4ff76156f4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
